### ISSUE TITLE
Do not loss original indentation

### ISSUE THREAD

**Issue by netizen-ais** [idleberg/atom-edit-in-new-tab#1]
After editing a code block in another tab, with sync mode, the code block in the original tab loses indentation. Not a great problem but it would be great to fix, as the main use I see for this package is to edit embedded different language code as a zoom/magnifyng glass tool.

**Comment by idleberg** [comment]
When I apply the formatting options in the package settings on the original tab, indentation still isn't respected. So, one solution might be disabling both indentation settings altogether.

Alternatively, I could add an option that runs Atom's built-in “Auto Indent” command every time the original tab is updated – but this would apply on the entire document, so it's not the same as maintaining indentation.

**Comment by idleberg** [comment]
Please take a look at the new package setting in the latest commit

**Comment by netizen-ais** [comment]
It seems to fix my use case. Thank you.
