### ISSUE TITLE
Allow multiple edits

### ISSUE THREAD

**Issue by Wombosvideo** [idleberg/atom-edit-in-new-tab#2]
Hey. I wanted to edit multiple snippets in my JS in different tabs. The problem is that it just writes back where the **cursor is instead of the original place**. I would really like the possibility to write back exactly where the snippet was instead of where my cursor/selection is.

Despite this `BUG` I really like this package ;-)

**Comment by idleberg** [comment]
I don't necessarily want to manage tabs or what happens, when a selection was destroyed (I already tried that), but I'll take a look at what [getSelections](https://atom.io/docs/api/v1.13.1/TextEditor#instance-getSelections) or [getSelectionsOrderedByBufferPosition](https://atom.io/docs/api/v1.13.1/TextEditor#instance-getSelectionsOrderedByBufferPosition) may provide to simplify the process. Anyway, I'll consider this is a feature request, clearly not a bug!
