### ISSUE TITLE
Edit indicator

### ISSUE THREAD

**Issue by Wombosvideo** [idleberg/atom-edit-in-new-tab#3]
Please add an indicator on line number ends (see _image_ below, where it is at line number start) to the lines which are currently edited in different tabs. This feature would however only make sense if #2 is "fixed" before. And if I can make a color recommendation it would be slightly light purplish.

[![Line was edited indicator by git-diff package](https://puu.sh/tJZm0/56cfa3e234.png)](https://puu.sh/tJZm0/56cfa3e234.png "Open image from puu.sh")
The [git-diff package](https://atom.io/packages/git-diff "Show package page") for and by [Atom](https://atom.io/) made the indicator in the image above. Have a peek on their code to see how they did it.

**Comment by idleberg** [comment]
It's not clear what you are asking for. If you're looking for a way to highlight selections, you can do so in `index.less`. There are also several packages for that.

**Comment by Wombosvideo** [comment]
I am looking for a way to highlight the edited lines (which were edited in other tabs and those tabs are currently still open) with an orange indicator (shown on the absolute left of the image on line 60).
But since git-diff uses the same color and position I would recommend to use the position at the end of the line number label instead and a purplish color instead so you still know which indicator is from git-diff and which one is from edit-in-new-tab.

By default lines should not have such an indicator (like the lines 58, 59, 61 and 62 also don't have any) but in the above mentioned cases they should so it's easier to determine the lines

**Comment by Wombosvideo** [comment]
But as I said, this feature doesn't make any sense if it is not possible to have multiple edit sessions at once which is why I am unhappily closing this
